### PR TITLE
Improve database structure and fix code errors

### LINKED ISSUE #24: Improve persistence layer as the plugin interacts with the database.
This issue is mainly concerning of the data model. For example, do we need to have both an idx and status_list_id on StatusListMappingEntity? Do we need to have two entities? Could you into this topic with a critic eye?

The StatusListProtocolMappers directly responsible for creating EntityManager instances, writing queries, and managing transactions. This violates the Single Responsibility Principle. Review the entire codebase and see how to manage Entity Relationships across the codebase.

### PR DESCRIPTION
**Pull request by Vitalisn4**
I cleaned up how the plugin saves data to the database to make it cleaner and more standard. 

**What I changed:**
*   **Deleted the "Ghost" File:** Removed `StatusListCounterEntity.java` because we didn't actually need a separate file just to count numbers.
*   **Better Database Table:** Updated `StatusListMappingEntity` to use a proper unique ID (UUID) for the row, while letting the database automatically handle the "Index Number" counting.
*   **No More Manual SQL:** Removed the manual `SELECT nextval` SQL query from the Java code. We now just save the object, and the database does the rest.

**Why this helps:**
*   The code is much simpler and easier to read.
*   It is safer because we aren't writing raw SQL commands manually.

Closes #24

### CODE REVIEW

**Review by IngridPuppet — CHANGES_REQUESTED** [review]
Hello @Vitalisn4 - Do you plan addressing these remaining two comments?

Image

Note to myself: I didn't re-review the other comments.

**Comment by Vitalisn4** [comment]
> Hello @Vitalisn4 - Do you plan addressing these remaining two comments?
> Image
> 
> Note to myself: I didn't re-review the other comments.

I am going to work on it sir

File: src/test/java/com/adorsys/keycloakstatuslist/StatusListProtocolMapperTest.java [hunk 1]
```diff
@@ -184,27 +185,26 @@ void shouldNotMap_IfCantPublishStatus() {
...
+    /**
+     * Mocks the EntityManager.persist() method.
+     * Use this instead of the old 'mockGetNextIndex'.
+     * This ensures the entity gets an ID and IDX assigned when the code saves it.
+     */
+    private void mockEntityPersist(long simulatedIndex) {
+        doAnswer(invocation -> {
+            StatusListMappingEntity entity = invocation.getArgument(0);
+            entity.setIdx(simulatedIndex); // Simulate sequence generation
+            entity.setId("test-uuid-" + simulatedIndex); // Simulate UUID generation
```
Comment (IngridPuppet) [inline src/test/java/com/adorsys/keycloakstatuslist/StatusListProtocolMapperTest.java]: Use module `UUID` to be more realistic.
```suggestion
            entity.setId(UUID.randomUUID().toString()); // Simulate UUID generation
```

**Review by IngridPuppet — CHANGES_REQUESTED** [review]
There are still comments unaddressed. Please check them carefully.
